### ISSUE TITLE
Polish issues

### ISSUE THREAD

**Issue by thomaswilburn** [mahirpiyarali/LaunchPad-D1#4]
Random notes for things that need to be improved or added to the project:

* The headline looks too small, and needs a better presentation. Maybe centered, with larger text? Alternately, you can put it over top of the image. we can talk about this on Tuesday.
* Add your last name
* Add an actual date for "originally published"
* The "key" block makes everything orange, which is kind of disorienting since you talk about black dots.
* You definitely don't need to say that cities appear behind a given block. Especially since depending on screen size, you don't actually know if they do.
* First quality of life item highlights everything as well--maybe it should highlight nothing?
* Hide the zoom control when the map is locked.
* Typo in the image caption: "throuhgout"

**Comment by mahirpiyarali** [comment]
Sounds good! I'm doing most of it right now. One extra note: I added a lot more to the conclusion, and I'm working on adding a few more blocks of text about a few more of Amazon's criteria. For some reason, I added in a new block on "cultural community fit", but the text in it gets cut off after a line or two? @thomaswilburn

**Comment by thomaswilburn** [comment]
I don't see that in the story.txt, can you specify which block is getting cut off?

**Comment by mahirpiyarali** [comment]
underneath cost of living, "title: Cultural Community Fit" @thomaswilburn

**Comment by thomaswilburn** [comment]
I don't see an `:end` tag, so it might be ending after the first line break.

**Comment by mahirpiyarali** [comment]
Hah, easy fix. Thanks! I'll send another message after making more changes! @thomaswilburn

**Comment by mahirpiyarali** [comment]
trying to hide zoom control when the map is locked, 

`var options = ["scrollWheelZoom", "touchZoom", "zoomControl"];`
`  var method = lock ? "disable" : "enable" : "false";`

but when I do this and save it throws an error. I'm looking at the leaflet docs and it says that `zoomControl` is a true-false boolean, what am I doing wrong? @thomaswilburn

**Comment by thomaswilburn** [comment]
The zoom control should be able to be enabled or disabled in that loop (I can call `map.zoomControl.disable()` manually, for example). However, this doesn't hide the zoom, it just puts it in the disabled state (grayed out and not responsive to touch). If you want to actually take it away and put it back, you may need to use `map.removeControl(map.zoomControl)` and `map.addControl(map.zoomControl)` based on the value of `lock`, instead of adding "zoomControl" to your options list.

**Comment by thomaswilburn** [comment]
Bear in mind, zoomControl is only a boolean in the original options hash that is passed to the map during instantiation. We're dealing with the runtime map here. If I add "zoomControl" to the options list, it does work for me.
